AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS resources for a Terraform backend
Parameters:
  Prefix:
    Type: String
    Description: The prefix for AWS resource names
  ProjectName:
    Type: String
    Description: The name of the project
  Environment:
    Type: String
    Description: The name of the environment
  KmsKeyArn:
    Type: String
    Description: The ARN of the KMS key that encrypts the bucket

Resources:
  TfBackendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Prefix}-${ProjectName}-tfstate-${Environment}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: 'aws:kms'
            KMSMasterKeyID: !Ref KmsKeyArn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  TfBackendDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Prefix}-${ProjectName}-tfstate-lock-${Environment}-${AWS::Region}
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S

Outputs:
  TfBackendBucket:
    Value: !Ref TfBackendBucket
  TfBackendDynamoDbTable:
    Value: !Ref TfBackendDynamoDbTable
