AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS resources for a Terraform backend
Parameters:
  Prefix:
    Type: String
    Description: The prefix for AWS resource names
  ProjectName:
    Type: String
    Description: The name of the project
  Environment:
    Type: String
    Description: The name of the environment

Resources:
  TfBackendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-${ProjectName}-tfstate-${Environment}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: sje:Purpose
          Value: terraform-backend

  TfBackendDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Prefix}-${ProjectName}-tfstate-lock-${Environment}-${AWS::Region}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      Tags:
        - Key: sje:Purpose
          Value: terraform-backend

Outputs:
  TfBackendBucket:
    Value: !GetAtt TfBackendBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-s3-state-${AWS::Region}"
  TfBackendDynamoDbTable:
    Value: !GetAtt TfBackendDynamoDbTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ddb-lock-${AWS::Region}"
 